services:

  api:
    build:
      context: api
      dockerfile: ./Dockerfile
    image: tibs-api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: tibs-api
    environment:
      - DEBUG=False
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=host.docker.internal
      - DB_NAME=postgres
      - WEB_SERVER_URL=http://web:3000
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  web: 
    build:
      context: web
      dockerfile: ./Dockerfile
    image: tibs-web
    container_name: tibs-web
    environment:
      - REACT_APP_API_SERVER_URL=REACT_APP_API_SERVER_URL=193.197.229.59:8000
    volumes:
      - /web/node_modules
      - ./web:/web
    expose: 
      - 3000
    ports: 
      - "3000:3000"
    command: npm start 

  mqtt-client:
    build:
      context: mqtt_client
      dockerfile: ./Dockerfile
    image: tibs-mqtt-client
    container_name: tibs-mqtt-client
    network_mode: "host"
    environment:
      - BROKER_IP_ADDRESS=https://broker.hivemq.com:1883
      - API_SERVER_URL=http://api:8000
    volumes:
      - ./mqtt_client:/mqtt_client
    depends_on:
      - api
    restart: on-failure
    #command: python3 mqtt_client.py
    command: tail -F anything  # use this command if you want to keep the container alive (it shuts down upon an error)

  db:
    image: postgres:14
    container_name: tibs-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
